### ISSUE TITLE
Make uFlash installable on the Raspberry Pi

### ISSUE THREAD

**Issue by ntoll** [ntoll/uflash#12]
One for @bennuttall perhaps..? Apart from Python 3, there are no further requirements.

See the documentation here:

http://uflash.readthedocs.org/en/latest/

This would be really useful since it will allow people to use whatever editor they like to create MicroPython scripts.

**Comment by ntoll** [comment]
@bennuttall ???

**Comment by bennuttall** [comment]
The pip install works on a Pi, right? So should just be a case of adding debian stuff and submitting to Raspbian.

**Comment by ntoll** [comment]
Closing in the hope that people know how to use pip. ;-)
