### ISSUE TITLE
Flash multiple microbits at once

### ISSUE THREAD

**Issue by tomviner** [ntoll/uflash#18]
Now that we have the radio module, there's an obvious need to flash multiple devices at once, when updating a microbit squadron with your new game.

Currently you can address non-default targets like `uflash race.py /media/tom/MICROBIT1` but it would be nice to have:
`uflash race.py /media/tom/MICROBIT /media/tom/MICROBIT1`

This would allow shell expansions like:
```bash
$ uflash race.py /media/tom/MICROBIT*
or
$ uflash race.py /media/tom/MICROBIT{,1,2}
```

Happy to write the patch if there's agreement on this feature.

**Comment by ntoll** [comment]
Make it so..! :-)

If you make a patch remember to update the docs and add yourself to the AUTHORS file.
