### ISSUE TITLE
PWM weirdness

### ISSUE THREAD

**Issue by jezdean** [ntoll/uflash#33]
[There's an issue raised in microbit micropython](https://github.com/bbcmicrobit/micropython/issues/391) repository and I think I've encountered something similar. A servo driver I wrote is now pointing all over the place. 

### Problem

Perhaps the best example of the issue is an LED. I used the following script:

#### Code
```
from microbit import pin0, sleep, display

display.scroll("1")

for i in range(0, 1023, 10):
    pin0.write_analog(i)
    sleep(100)


display.scroll("2")

pin0.set_analog_period(5)
for i in range(0, 1023, 10):
    pin0.write_analog(i)
    sleep(100)
```

#### Video

[there's a video of it here](https://vid.me/IkEq).

Both flicker but the first is slightly worse.

#### Reproduced in

(all examples below return `>>> MicroPython  v1.7-9-gbe020eb on 2016-04-18; micro:bit with nRF51822` as their version) 

Reproduced in:

* microbit.org.uk editor
* mu-2016-07-03_19_19_01
* mu-2016-07-31_23_01_47.exe
* mu-2016-08-13_20_40_52.exe
* mu-2016-10-15_13_20_00.exe
* mu-2016-11-14_08_54_40.exe
* mu-2016-12-23_14_19_21.exe
* current version of uflash.

Not Reproduced in:

* microbit.co.uk editor
* mu-2016-05-04-07-19-54.exe
* mu-2016-06-23_18_11_29.exe
* mu-2016-06-27_05_46_19.exe

### Thoughts

It stops working between two sequential windows builds listed on the amazon cloud: 27-06-2016 and 03-07-2016.  

Perhaps [this commit in mu?](https://github.com/mu-editor/mu/commit/ff8182f7b40b0574ad7ba867160f7edbd27d81ca) and [this one in uflash?](https://github.com/ntoll/uflash/commit/04afb7e9c7118a7d56f1f2b2328fe9162a26c24e). The runtime was updated.

`.hex` files flashed in the current version of uflash still flicker. I can checkout old versions of uflash but I cannot get it to flash a `.hex`. Not sure why.

[There was an issue with PWM weirdness](https://github.com/bbcmicrobit/micropython/issues/331) when they introduced to speech module.  Perhaps that?

**Comment by ntoll** [comment]
Fixed with latest firmware update.
