### ISSUE TITLE
Update to latest firmware

### ISSUE THREAD

**Issue by dpgeorge** [ntoll/uflash#34]
It looks like the firmware of uflash is built from 24th Oct 2016 (correct me if I'm wrong!).  There have been some important bug fixes since then (notably PWM) and it would be great to update the firmware to the latest (also in mu).

**Comment by carlosperate** [comment]
As an additional note, since we still don't have proper versioning in the micro:bit micropython, it would be great if at least the CHANGES.rst could contain the hash and date of the micropython version.

**Comment by ntoll** [comment]
Hi... I believe the following issue / PR needs addressing before we can update the firmware. The pin update breaks several bot / hardware kits that use the affected pins:

https://github.com/bbcmicrobit/micropython/pull/397

@dpgeorge any thoughts on this..?

**Comment by dpgeorge** [comment]
> The pin update breaks several bot / hardware kits that use the affected pins:

Agreed that needs fixing.  See also https://github.com/bbcmicrobit/micropython/pull/398 for a similar issue.

> As an additional note, since we still don't have proper versioning in the micro:bit micropython, it would be great if at least the CHANGES.rst could contain the hash and date of the micropython version.

Yes we definitely need to properly track the exact version of the microbit build.

**Comment by tim1mw** [comment]
An update to the uflash firmware would be handy for a project I'm working on. The version supplied in uflash (and mu) crashes if PWM output and the radio receiver are user together. See:

https://github.com/bbcmicrobit/micropython/issues/380

**Comment by tim1mw** [comment]
I've created a fork which includes the latest microbit micropython code, see https://github.com/tim1mw/uflash . This seems to solve the PWM+radio crash, but it does exhibit the pin mode problem. I've worked around this in my own code, but I'm assuming this needs to be solved before it can go into the main version of uflash and mu.

**Comment by ntoll** [comment]
OK... latest version of firmware is in master and release 1.1 on PyPI.
