### ISSUE TITLE
Error when flashing a Python script

### ISSUE THREAD

**Issue by simulsys** [ntoll/uflash#42]
Hi,

I am trying to flash a Python script but get the following error:

ushort format requires 0 <= number <= (0x7fff * 2 + 1)

What does this mean, please, and how do I get around it?
Many thanks,
Andrew.

**Comment by carlosperate** [comment]
Hi Andrew,

Which command were you using to flash the script? Could you copy/paste the entire console contents when that happens?

**Comment by simulsys** [comment]
Hi Carlos,

Many thanks for your response. It turned out I was using too large a Python script with non-uasab;e modules, which uflash did not accept. I have amended the code to within the usable constraints.
Cheers,
