### ISSUE TITLE
Is it possible to flash several .py files simultaneously?

### ISSUE THREAD

**Issue by HochulHwang** [ntoll/uflash#55]
This is my shell script to run the files simultaneously. bright.py file is imported in resistance.py. However, I get an import error that there is no such module bright. What could be the problem?

```
COMMAND1="uflash resistance.py" 
COMMAND2="uflash bright.py"
$COMMAND2 & $COMMAND1 &
```

**Comment by ntoll** [comment]
Sadly, due to limitations of the micro:bit this isn't available in uflash. However, the Mu editor allows you to copy over modules, which is probably what you want/need.
