### ISSUE TITLE
flashing a script is different from putting a main.py

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/uflash#60]
I was trying a test program. I plan to have a large file so thought i'd give it a dummy run.
if i flash my script like this `uflash test_fs.py` .  When the script executes it crashes with `OSError: 28`.
When i flash a blank micropython.hex `uflash` then put my script as main.py `ufs put test_fs.py main.py` it executes ok.
Here's a copy of the program which crashes:
[test_fs.py.txt](https://github.com/ntoll/uflash/files/2686362/test_fs.py.txt)

**Comment by ntoll** [comment]
This isn't a bug with uflash. This is a bug with MicroPython on the micro:bit. Could you please report it to that project please..?

https://github.com/bbcmicrobit/micropython

Thank you.
