### ISSUE TITLE
Add ability to extract Python code from a .hex file.

### ISSUE THREAD

**Issue by ntoll** [ntoll/uflash#7]
Because sometimes, you don't save the source file... ;-)

**Comment by funkyHat** [comment]
So I've written 2 functions for this on https://github.com/funkyHat/uflash/tree/unhexlify

They look good for getting the script back out of a .hex file that was saved somewhere (I'm not sure if it's easy or not to get a flashed .hex back out of a micro:bit so I'm ignoring that for now :)).

The last bit is the command line interface.

I think it makes sense to switch to using argparse (or perhaps click? But argparse is in the standard library). @ntoll what do you think?

**Comment by ntoll** [comment]
Send it as a PR and I'll review. THIS IS TOTALLY AWESOME!!!

Agree about arg parsing. Path of least dependencies is good too.

:+1: :smile:

**Comment by funkyHat** [comment]
So I've updated my branch with the argparse code and a few more tests. Every time I try to rebase though my "unhexlify()" function is disappearing? Weird.

Still trying...

**Comment by funkyHat** [comment]
Ah think I've got it :)
