### ISSUE TITLE
uflash : The term 'uflash' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by juliano-gouveia** [ntoll/uflash#84]
![image](https://user-images.githubusercontent.com/42938517/232874167-3fdc4946-3dea-4b0d-a0e2-f218c413d5c4.png)

**Comment by ntoll** [comment]
Unless you give more information about this, there's not a lot can be done.

**Comment by juliano-gouveia** [comment]
when i do uflash -h it displays that error
